'use client';
import {useEffect,useState} from 'react';
export function AuthControls(){
 const [user,setUser]=useState<{id:string;username:string}|null>(null);const [open,setOpen]=useState<'login'|'register'|null>(null);const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const load=async()=>{const r=await fetch('/api/auth/me',{cache:'no-store'});const d=await r.json();setUser(d.user);};
 useEffect(()=>{load();const f=()=>load();window.addEventListener('blox:auth',f);return()=>window.removeEventListener('blox:auth',f)},[]);
 async function submit(){setBusy(true);setError('');try{const r=await fetch(`/api/auth/${open}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const d=await r.json();if(!r.ok)throw new Error(d.error);setUser(d.user);setOpen(null);setUsername('');setPassword('');window.dispatchEvent(new Event('blox:auth'));}catch(e){setError(e instanceof Error?e.message:'Erreur')}finally{setBusy(false)}}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});setUser(null);window.dispatchEvent(new Event('blox:auth'));}
 return <div className="auth-area"><a href="/admin" className="pill" style={{textDecoration:'none'}}>⚙ Admin</a>{user?<><span className="pill">👤 {user.username}</span><button className="pill" onClick={logout}>Déconnexion</button></>:<><button className="pill" onClick={()=>{setOpen('login');setError('')}}>Login</button><button className="pill" onClick={()=>{setOpen('register');setError('')}}>Register</button></>}{open&&<div className="auth-pop"><strong>{open==='login'?'Connexion':'Créer un compte'}</strong><input className="field" placeholder="Pseudo" value={username} onChange={e=>setUsername(e.target.value)}/><input className="field" type="password" placeholder="Mot de passe" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<small>{error}</small>}<button className="playbtn" onClick={submit} disabled={busy}>{busy?'...':open==='login'?'Se connecter':'Créer le compte'}</button></div>}</div>
}
