import { Redis } from '@upstash/redis';
const redis = new Redis({url:process.env.UPSTASH_REDIS_REST_URL!, token:process.env.UPSTASH_REDIS_REST_TOKEN!});
const profileKey=(id:string)=>`blox:profile:${id}`;
const historyKey=(id:string)=>`blox:user:history:${id}`;
const inventoryKey=(id:string)=>`blox:inventory:${id}`;
const notifKey=(id:string)=>`blox:notifications:${id}`;
const levelFor=(xp:number)=>Math.max(1,Math.floor(Math.sqrt(Math.max(0,xp)/100))+1);
const dayKey=()=>new Date().toISOString().slice(0,10);
function weekKey(){const d=new Date();const one=new Date(Date.UTC(d.getUTCFullYear(),0,1));const week=Math.ceil((((d.getTime()-one.getTime())/86400000)+one.getUTCDay()+1)/7);return `${d.getUTCFullYear()}-W${String(week).padStart(2,'0')}`;}
export type Profile={id:string;username:string;xp:number;level:number;wins:number;losses:number;totalWon:number;totalLost:number;games:number;streak:number;bestStreak:number;createdAt:number;avatar:string;frame:string;badge:string};
export const COSMETICS=[{id:'avatar-rocket',type:'avatar',name:'Rocket',value:'🚀',cost:150},{id:'avatar-crown',type:'avatar',name:'Crown',value:'👑',cost:300},{id:'avatar-fire',type:'avatar',name:'Fire',value:'🔥',cost:500},{id:'frame-neon',type:'frame',name:'Neon',value:'neon',cost:400},{id:'frame-gold',type:'frame',name:'Gold',value:'gold',cost:700},{id:'badge-pro',type:'badge',name:'PRO',value:'PRO',cost:1000},{id:'badge-whale',type:'badge',name:'WHALE',value:'WHALE',cost:2500}] as const;
export async function getProfile(id:string,username:string,createdAt:number){const p=await redis.get<Profile>(profileKey(id));if(p)return {...p,username};const fresh:Profile={id,username,xp:0,level:1,wins:0,losses:0,totalWon:0,totalLost:0,games:0,streak:0,bestStreak:0,createdAt,avatar:'🙂',frame:'default',badge:''};await redis.set(profileKey(id),fresh,{nx:true});return fresh;}
export async function addResult(id:string,username:string,createdAt:number,game:string,type:'win'|'loss',amount:number){const p=await getProfile(id,username,createdAt);const xp=Math.max(5,Math.min(250,Math.floor(Math.abs(amount)/10)+20));const next={...p,games:p.games+1,xp:p.xp+xp,level:levelFor(p.xp+xp),wins:p.wins+(type==='win'?1:0),losses:p.losses+(type==='loss'?1:0),totalWon:p.totalWon+(type==='win'?Math.max(0,amount):0),totalLost:p.totalLost+(type==='loss'?Math.abs(amount):0),streak:type==='win'?p.streak+1:0,bestStreak:type==='win'?Math.max(p.bestStreak,p.streak+1):p.bestStreak};await redis.set(profileKey(id),next);const item={id:crypto.randomUUID(),game,type,amount,createdAt,username};await redis.lpush(historyKey(id),item);await redis.ltrim(historyKey(id),0,49);await redis.zincrby(`blox:leaderboard:daily:${dayKey()}`,xp,id);await redis.zincrby(`blox:leaderboard:weekly:${weekKey()}`,xp,id);if(next.level>p.level)await pushNotification(id,`🎉 Niveau ${next.level} atteint !`);return next;}
export async function pushNotification(id:string,text:string){const item={id:crypto.randomUUID(),text,createdAt:Date.now()};await redis.lpush(notifKey(id),item);await redis.ltrim(notifKey(id),0,19);return item;}
export async function claimDaily(id:string,username:string,createdAt:number){const lock=await redis.set(`blox:daily:${id}`,'1',{nx:true,ex:86400});if(!lock)return {ok:false as const,reason:'already'};const p=await getProfile(id,username,createdAt);const streak=p.streak+1;const bonus=100+Math.min(500,streak*50);const next={...p,xp:p.xp+bonus,level:levelFor(p.xp+bonus)};await redis.set(profileKey(id),next);await pushNotification(id,`🎁 Daily Reward : +${bonus} XP`);return {ok:true as const,bonus,profile:next};}
export async function buyCosmetic(id:string,username:string,createdAt:number,cosmeticId:string){const item=COSMETICS.find(x=>x.id===cosmeticId);if(!item)return {ok:false as const,error:'Cosmétique introuvable.'};const owned=await redis.sismember(inventoryKey(id),cosmeticId);if(owned)return {ok:false as const,error:'Déjà possédé.'};const p=await getProfile(id,username,createdAt);if(p.xp<item.cost)return {ok:false as const,error:'XP insuffisante.'};const next={...p,xp:p.xp-item.cost,level:levelFor(p.xp-item.cost)};await redis.set(profileKey(id),next);await redis.sadd(inventoryKey(id),cosmeticId);await pushNotification(id,`🛍️ ${item.name} débloqué !`);return {ok:true as const,profile:next,item};}
export async function setCosmetic(id:string,field:'avatar'|'frame'|'badge',value:string){const p=await redis.get<Profile>(profileKey(id));if(!p)return null;const next={...p,[field]:value};await redis.set(profileKey(id),next);return next;}
export async function getInventory(id:string){return (await redis.smembers(inventoryKey(id))) as unknown as string[];}
export async function getUserHistory(id:string){return (await redis.lrange(historyKey(id),0,49))||[];}
export async function getNotifications(id:string){return (await redis.lrange(notifKey(id),0,19))||[];}
export async function leaderboard(period:'daily'|'weekly'){const key=period==='daily'?`blox:leaderboard:daily:${dayKey()}`:`blox:leaderboard:weekly:${weekKey()}`;const ids=await redis.zrange(key,0,9,{rev:true}) as unknown as string[];const out=[];for(const id of ids){const p=await redis.get<Profile>(profileKey(id));if(p)out.push({username:p.username,xp:p.xp,level:p.level});}return out;}
