import {Redis} from '@upstash/redis';
let redis:Redis|null=null;function getRedis(){if(redis)return redis;const url=process.env.UPSTASH_REDIS_REST_URL,token=process.env.UPSTASH_REDIS_REST_TOKEN;if(!url||!token)throw new Error('UPSTASH_REDIS_REST_URL / UPSTASH_REDIS_REST_TOKEN missing');redis=new Redis({url,token});return redis;}
export type ShopOrder={requestId:string;productId:string;price:number;key:string;status:'pending'|'delivered';createdAt:number;deliveredAt?:number;account?:string};
const orderKey=(id:string)=>`blox:shop:order:${id}`,stockKey=(productId:string)=>`blox:shop:stock:${productId}`,availableKeysKey=(productId:string)=>`blox:shop:keys:${productId}`,lockKey=(id:string)=>`blox:shop:delivery-lock:${id}`;
export async function saveOrder(order:ShopOrder){await getRedis().set(orderKey(order.requestId),JSON.stringify(order));}
export async function getOrder(requestId:string){const raw=await getRedis().get<string>(orderKey(requestId));if(!raw)return null;return typeof raw==='string'?JSON.parse(raw):raw as unknown as ShopOrder;}
export async function addStock(productId:string,accounts:string[]){const clean=accounts.map(x=>x.trim()).filter(Boolean);if(!clean.length)return 0;await getRedis().rpush(stockKey(productId),...clean);return clean.length;}
export async function stockCount(productId:string){return await getRedis().llen(stockKey(productId));}
export async function addGeneratedKeys(productId:string,keys:string[]){const clean=keys.map(x=>x.trim()).filter(Boolean);if(!clean.length)return 0;await getRedis().rpush(availableKeysKey(productId),...clean);return clean.length;}
export async function availableKeyCount(productId:string){return await getRedis().llen(availableKeysKey(productId));}
export async function takeGeneratedKey(productId:string){return await getRedis().lpop<string>(availableKeysKey(productId));}
export async function deliverOrder(requestId:string){const r=getRedis();const locked=await r.set(lockKey(requestId),'1',{nx:true,ex:30});if(!locked)return {ok:false as const,reason:'busy' as const};try{const order=await getOrder(requestId);if(!order)return {ok:false as const,reason:'not_found' as const};if(order.status==='delivered')return {ok:false as const,reason:'already_delivered' as const,order};const account=await r.lpop<string>(stockKey(order.productId));if(!account)return {ok:false as const,reason:'out_of_stock' as const,order};const updated={...order,status:'delivered' as const,deliveredAt:Date.now(),account};await saveOrder(updated);return {ok:true as const,order:updated};}finally{await r.del(lockKey(requestId));}}
