'use client';
import {useEffect,useRef,useState} from 'react';
import {addCoins,getCoins,spendCoins} from '@/lib/wallet';
type HistoryItem={id:string;roundId:string;username:string;type:'win'|'loss';amount:number;payout:number;bet:number;multiplier:number;createdAt:number};
type State={id:string;phase:'waiting'|'running';startedAt:number;runAt?:number|null;crashAt:number;username?:string|null;history:HistoryItem[];bet:number;cashedOut:boolean;payout:number;multiplier?:number};
export function Rocket(){
 const [bet,setBet]=useState(100),[mult,setMult]=useState(1),[state,setState]=useState<State|null>(null),[msg,setMsg]=useState('La prochaine manche ouvre les mises pendant 5 secondes.'),[placed,setPlaced]=useState(false),[cashing,setCashing]=useState(false),[history,setHistory]=useState<HistoryItem[]>([]),[waitingSeconds,setWaitingSeconds]=useState(5),[logged,setLogged]=useState(false);const timerRef=useRef<ReturnType<typeof setInterval>|null>(null);
 const load=async()=>{try{const r=await fetch('/api/rocket',{cache:'no-store',credentials:'include'});if(r.status===401){setLogged(false);return}if(r.ok){const raw=await r.json() as State;setLogged(Boolean(raw.username));setState(raw);setHistory(raw.history||[]);setPlaced(Boolean(raw.bet>0&&!raw.cashedOut))}}catch{}};
 useEffect(()=>{load();const auth=()=>load();window.addEventListener('blox:auth',auth);const poll=setInterval(load,200);return()=>{clearInterval(poll);window.removeEventListener('blox:auth',auth);if(timerRef.current)clearInterval(timerRef.current)}},[]);
 useEffect(()=>{if(!state)return;const tick=()=>{const now=Date.now();if(state.phase==='waiting'){setMult(1);const left=Math.max(0,state.startedAt+5000-now);setWaitingSeconds(left/1000);setMsg(`🚀 Prochaine partie dans ${Math.max(0,left/1000).toFixed(1)}s`)}else{setWaitingSeconds(0);const elapsed=Math.max(0,now-(state.runAt??state.startedAt));const m=Number((1+elapsed/10500).toFixed(2)),crash=state.crashAt/100;if(m>=crash){setMult(crash);setMsg(`💥 Explosion à ×${crash.toFixed(2)} — nouvelle manche en préparation…`)}else{setMult(m);setMsg(state.cashedOut?`✅ Encaissé à ×${state.payout&&state.bet?(state.payout/state.bet).toFixed(2):'1.00'}`:'🚀 En vol — encaisse avant l’explosion !')}}};tick();timerRef.current=setInterval(tick,50);return()=>{if(timerRef.current)clearInterval(timerRef.current)}},[state]);
 const placeBet=async()=>{const b=Math.floor(Number(bet));if(!Number.isFinite(b)||b<10){setMsg('Mise minimum : 10 coins.');return}if(placed){setMsg('Tu as déjà une mise active.');return}if(!state||state.phase!=='waiting'){setMsg('Les mises sont fermées.');return}if(!spendCoins(b)){setMsg('Coins insuffisants.');return}setPlaced(true);try{const r=await fetch('/api/rocket',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({action:'bet',bet:b})}),data=await r.json().catch(()=>({}));if(!r.ok){addCoins(b);setPlaced(false);setMsg(data.error||'Mise refusée.');await load();return}setState(data);setHistory(data.history||[]);setPlaced(Boolean(data.bet>0&&!data.cashedOut));setMsg('✅ Mise enregistrée. La fusée est solo.')}catch{addCoins(b);setPlaced(false);setMsg('Serveur indisponible.');await load()}};
 const cashout=async()=>{if(cashing)return;setCashing(true);try{const r=await fetch('/api/rocket',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({action:'cashout'})}),data=await r.json().catch(()=>({}));if(!r.ok){setMsg(data.error||'Encaissement refusé.');await load();return}setState(data);setHistory(data.history||[]);setPlaced(false);addCoins(Number(data.payout)||0);setMsg(`🎉 Encaissement confirmé : +${Number(data.payout||0).toLocaleString('fr-BE')} coins à ×${Number(data.multiplier||1).toFixed(2)}.`)}catch{setMsg('Serveur indisponible.');await load()}finally{setCashing(false)}};
 const waiting=state?.phase==='waiting',hasActiveBet=Boolean(state&&state.bet>0&&!state.cashedOut),localCoins=getCoins();return <div className="rocket-game-stage game-panel"><div className="rocket-head"><div><div className="game-kicker">ARCADE / ROCKET SOLO</div><h2>🚀 Rocket Solo</h2><p className="muted">La fusée redémarre automatiquement après chaque explosion.</p></div><div className="rocket-head-mult">×{mult.toFixed(2)}</div></div><div className={`rocket-stage ${state?.phase==='running'?'rocket-running':''}`}><div className="rocket-stars"/><div className="rocket-grid"/><div className="rocket-glow"/><div className="rocket-trail"/><div className="rocket-flight-line"/><div className="rocket"><span>🚀</span></div><strong className="rocket-stage-mult">×{mult.toFixed(2)}</strong><div className="rocket-status">{waiting?`MISES OUVERTES · ${waitingSeconds.toFixed(1)}s`:state?.phase==='running'?'EN VOL':'PRÊT'}</div><div className="rocket-solo-info"><strong>🎯 Mode solo</strong><span>Chaque manche est indépendante et redémarre automatiquement.</span></div><div className="rocket-history"><div className="rocket-players-title">📈 HISTORIQUE EN DIRECT</div><div className="rocket-history-list">{history.length===0?<span className="rocket-empty">Les gains et pertes apparaîtront ici.</span>:history.slice(0,8).map(h=><div className={`rocket-history-item ${h.type}`} key={h.id}><span><b>{h.username}</b> {h.type==='win'?'a gagné':'a perdu'}</span><strong>{h.amount>=0?'+':''}{h.amount.toLocaleString('fr-BE')} 🪙</strong></div>)}</div></div></div><div className="rocket-controls"><div className="rocket-bet"><label>Mise</label><div className="rocket-input-row"><div className="rocket-input-wrap"><span>🪙</span><input className="field" type="number" min="10" value={bet} onChange={e=>setBet(Number(e.target.value))} disabled={!waiting||placed}/></div><button className="maxbtn" onClick={()=>setBet(localCoins)} disabled={!waiting||placed||localCoins<10}>MAX</button></div></div>{!logged?<a className="playbtn rocket-play rocket-login-btn" href="/login">🔐 Connecte-toi pour miser</a>:waiting?<button className="playbtn rocket-play" onClick={placeBet} disabled={placed||localCoins<10}>{placed?'✅ Mise placée':'🚀 Miser sur la prochaine'}</button>:<button className="cashbtn rocket-play" onClick={cashout} disabled={!hasActiveBet||cashing}>{cashing?'Encaissement…':'🚪 Quitter la fusée'}</button>}</div><p className="rocket-message muted">{msg}</p><p className="muted" style={{marginTop:8,fontSize:12}}>{logged?`Solde : ${localCoins.toLocaleString('fr-BE')} 🪙`:'Connecte-toi pour avoir un solde et miser.'}</p></div>}
